name: afritality
description: The online version of Afritality.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2
  simple_animations: ^1.3.3
  curved_navigation_bar: ^0.3.2
  firebase_core: ^0.5.1
  firebase_storage: ^5.0.1
  image_cropper: ^1.2.2
  image_picker: ^0.6.6+1
  time_ago_provider: ^1.0.3
  intl: ^0.16.1
  folding_cell: ^0.1.2
  charts_flutter: ^0.9.0
  cached_network_image: ^2.1.0+1
  share: ^0.6.4
  flip_card: ^0.4.4
  firebase_crashlytics: ^0.1.3+3
  progress_dialog: ^1.2.4
  youtube_player_flutter: ^7.0.0+7
  image: ^2.0.7
  animator: 0.1.4
  timeago: ^2.0.27
  geolocator: 5.0.1
  uuid: ^2.0.0
  path_provider: ^1.6.7
  firebase_messaging: ^4.0.0+1
  flutter_svg:
  url_launcher: ^5.4.11
  rflutter_alert: ^1.1.0
  purchases_flutter: ^1.4.0
  in_app_purchase: ^0.3.4+15
  mailer: ^3.2.1


  carousel_slider: ^2.2.1
  google_fonts: ^1.1.0
  file_picker: ^1.12.0
  advance_pdf_viewer: ^1.2.0
  circular_reveal_animation: ^1.1.5
  date_range_picker: ^1.0.5
  font_awesome_flutter: ^8.10.0
  bubble: ^1.1.9+1
  flutter_inapp_purchase: ^2.2.0
  google_sign_in: ^4.5.6

  pin_code_fields: ^6.1.0
  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/